# Generated by Django 4.2.30 on 2026-08-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_portfolio_id_alter_stockholding_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='wallet_balance',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.portfolio')),
            ],
        ),
    ]
