# Generated by Django 3.1.3 on 2021-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_stockholding_buying_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholding',
            name='buying_values',
            field=models.JSONField(default=list, blank=True),
            preserve_default=False,
        ),
    ]
