"""Add wallet_ledger table (CLAUDE.md v2 section 5.2)

Revision ID: 068462490cae
Revises: 86c9d03ab2f3
Create Date: 2026-08-05 15:27:48.351971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068462490cae'
down_revision = '86c9d03ab2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_ledger',
    sa.Column('ledger_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('entry_type', sa.String(length=15), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("entry_type IN ('DEPOSIT','WITHDRAWAL','BUY','SELL','DIVIDEND','FEE')", name='ck_wallet_entry_type'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('ledger_id')
    )
    with op.batch_alter_table('wallet_ledger', schema=None) as batch_op:
        batch_op.create_index('idx_wallet_created', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_ledger', schema=None) as batch_op:
        batch_op.drop_index('idx_wallet_created')

    op.drop_table('wallet_ledger')
    # ### end Alembic commands ###
