"""add market_index_constituents table

Revision ID: 0e654c4d5973
Revises: 068462490cae
Create Date: 2026-08-05 20:46:27.796015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e654c4d5973'
down_revision = '068462490cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_index_constituents',
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('index_name', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.asset_id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'index_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_index_constituents')
    # ### end Alembic commands ###
