"""add price_targets for in-app alerts

Revision ID: 4f8f653c5223
Revises: 963f2db78d94
Create Date: 2026-08-06 01:56:27.747607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8f653c5223'
down_revision = '963f2db78d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_targets',
    sa.Column('target_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("direction IN ('ABOVE','BELOW')", name='ck_price_target_direction'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.asset_id'], ),
    sa.PrimaryKeyConstraint('target_id')
    )
    with op.batch_alter_table('price_targets', schema=None) as batch_op:
        batch_op.create_index('idx_price_target_asset', ['asset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_targets', schema=None) as batch_op:
        batch_op.drop_index('idx_price_target_asset')

    op.drop_table('price_targets')
    # ### end Alembic commands ###
