"""Initial schema per CLAUDE.md section 5

Revision ID: 86c9d03ab2f3
Revises: 
Create Date: 2026-08-05 11:37:47.283327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c9d03ab2f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_metadata',
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('asset_type', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), server_default='INR', nullable=False),
    sa.Column('price_source', sa.String(length=10), server_default='LIVE', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("asset_type IN ('STOCK','MUTUAL_FUND','BOND')", name='ck_asset_type'),
    sa.CheckConstraint("price_source IN ('LIVE','MANUAL')", name='ck_price_source'),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('isin'),
    sa.UniqueConstraint('symbol', 'asset_type', name='uq_asset_symbol_type')
    )
    with op.batch_alter_table('asset_metadata', schema=None) as batch_op:
        batch_op.create_index('idx_meta_type', ['asset_type'], unique=False)

    op.create_table('fund_houses',
    sa.Column('fund_house_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('fund_house_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fund_managers',
    sa.Column('manager_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('manager_id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('asset_metrics',
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('metric_key', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('as_of', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.asset_id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'metric_key', 'period')
    )
    with op.batch_alter_table('asset_metrics', schema=None) as batch_op:
        batch_op.create_index('idx_metrics_key', ['metric_key'], unique=False)

    op.create_table('bond_details',
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('issuer', sa.String(length=150), nullable=True),
    sa.Column('coupon_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('face_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('credit_rating', sa.String(length=10), nullable=True),
    sa.Column('payment_frequency', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.asset_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('holdings',
    sa.Column('holding_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('avg_buy_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('first_bought', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('quantity >= 0', name='ck_holding_quantity_nonneg'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.asset_id'], ),
    sa.PrimaryKeyConstraint('holding_id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index('idx_holdings_asset', ['asset_id'], unique=False)

    op.create_table('mutual_fund_details',
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('fund_house_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('sub_category', sa.String(length=80), nullable=True),
    sa.Column('plan_type', sa.String(length=10), nullable=True),
    sa.Column('option_type', sa.String(length=10), nullable=True),
    sa.Column('expense_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('aum', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('benchmark', sa.String(length=120), nullable=True),
    sa.CheckConstraint("option_type IN ('GROWTH','IDCW')", name='ck_mf_option_type'),
    sa.CheckConstraint("plan_type IN ('DIRECT','REGULAR')", name='ck_mf_plan_type'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.asset_id'], ),
    sa.ForeignKeyConstraint(['fund_house_id'], ['fund_houses.fund_house_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('news_cache',
    sa.Column('news_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=700), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment', sa.String(length=10), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=700), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.asset_id'], ),
    sa.PrimaryKeyConstraint('news_id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('news_cache', schema=None) as batch_op:
        batch_op.create_index('idx_news_asset', ['asset_id'], unique=False)
        batch_op.create_index('idx_news_published', ['published_at'], unique=False)

    op.create_table('price_history',
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.asset_id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'price_date')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('idx_price_history_date', ['asset_id', 'price_date'], unique=False)

    op.create_table('price_snapshot',
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('prev_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('day_change', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('day_change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_stale', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.asset_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('sips',
    sa.Column('sip_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=15), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('day_of_cycle', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("frequency IN ('DAILY','WEEKLY','MONTHLY','QUARTERLY')", name='ck_sip_frequency'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.asset_id'], ),
    sa.PrimaryKeyConstraint('sip_id')
    )
    op.create_table('stock_details',
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.asset_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('watchlist',
    sa.Column('watchlist_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.asset_id'], ),
    sa.PrimaryKeyConstraint('watchlist_id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('fund_manager_assignments',
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('manager_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('since_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['mutual_fund_details.asset_id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['fund_managers.manager_id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'manager_id')
    )
    op.create_table('holding_tags',
    sa.Column('holding_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tag_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.holding_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('holding_id', 'tag_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('holding_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sip_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('txn_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fees', sa.Numeric(precision=12, scale=4), server_default='0', nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("txn_type IN ('BUY','SELL','DIVIDEND')", name='ck_txn_type'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.asset_id'], ),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.holding_id'], ),
    sa.ForeignKeyConstraint(['sip_id'], ['sips.sip_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_txn_asset', ['asset_id'], unique=False)
        batch_op.create_index('idx_txn_date', ['txn_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_txn_date')
        batch_op.drop_index('idx_txn_asset')

    op.drop_table('transactions')
    op.drop_table('holding_tags')
    op.drop_table('fund_manager_assignments')
    op.drop_table('watchlist')
    op.drop_table('stock_details')
    op.drop_table('sips')
    op.drop_table('price_snapshot')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('idx_price_history_date')

    op.drop_table('price_history')
    with op.batch_alter_table('news_cache', schema=None) as batch_op:
        batch_op.drop_index('idx_news_published')
        batch_op.drop_index('idx_news_asset')

    op.drop_table('news_cache')
    op.drop_table('mutual_fund_details')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index('idx_holdings_asset')

    op.drop_table('holdings')
    op.drop_table('bond_details')
    with op.batch_alter_table('asset_metrics', schema=None) as batch_op:
        batch_op.drop_index('idx_metrics_key')

    op.drop_table('asset_metrics')
    op.drop_table('tags')
    op.drop_table('fund_managers')
    op.drop_table('fund_houses')
    with op.batch_alter_table('asset_metadata', schema=None) as batch_op:
        batch_op.drop_index('idx_meta_type')

    op.drop_table('asset_metadata')
    # ### end Alembic commands ###
