# Generated by Django 6.0.7 on 2026-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskprofile', '0002_auto_20210316_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
